stages:
  - packer
  - docker
  - deploy-dev
  - deploy-test
  - packer-prd
  - docker-prd
  - deploy-prd

variables:
  DOCKER_HOST: tcp://localhost:2375/
  IMAGE: registry.cn-hangzhou.aliyuncs.com/masa/masa-blazor-docs:0.2.$CI_PIPELINE_ID
  IMAGEWASM: registry.cn-hangzhou.aliyuncs.com/masa/masa-blazor-docs:0.2.$CI_PIPELINE_ID-wasm
  IMAGE_PRD: registry.cn-hangzhou.aliyuncs.com/masa/masa-blazor-docs:$CI_COMMIT_TAG
  IMAGEWASM_PRD: registry.cn-hangzhou.aliyuncs.com/masa/masa-blazor-docs:$CI_COMMIT_TAG-wasm

packer:
  # image: proget-hz.lonsid.cn/masa-blazor/dotnet/sdk:6.0-forlinux
  #image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0-nodejs14.17.6
  image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0.100-preview.7-nodejs14.16.1
  stage: packer
  only:
    - develop 
  script:
    - ls 
    - ls src/
    - node -v
    - dotnet --version
    - git clone -b develop http://gitlab-hz.lonsid.cn/MASA-Stack/Framework/BlazorComponent.git ./src/BlazorComponent
    - dotnet workload install wasm-tools
    - dotnet build src
    - dotnet pack src --include-symbols -p:PackageVersion=0.2.$CI_PIPELINE_ID
    - dotnet nuget push "**/*.symbols.nupkg" -k $nugetkey -s https://api.nuget.org/v3/index.json
  artifacts:
    expire_in: 1 day
    paths:
      - ./src/BlazorComponent
  retry: 2

docker:
  image: docker:17.05.0
  stage: docker
  only:
    - develop
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN
  services:
    - name: registry.cn-hangzhou.aliyuncs.com/masa/library:docker-17.05.01-dind
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE
    - docker build -f Dockerfile.wasm -t $IMAGEWASM .
    - docker push $IMAGEWASM
  retry: 2

deploy-dev:
  # image: proget-hz.lonsid.cn/masa-images/library/kubectl:1.17.2-newack
  image: registry.cn-hangzhou.aliyuncs.com/masa/kubectl:1.17.2-masa-ack-dev
  stage: deploy-dev
  only:
    - develop
  script:
    - kubectl set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE -n masa-blazor
    - kubectl set image deployment/masa-blazor-docs-wasm masa-blazor-docs-wasm=$IMAGEWASM -n masa-blazor
  retry: 2
  
deploy-test:
  image: registry.cn-hangzhou.aliyuncs.com/masa/kubectl:1.17.2-masa-ack-dev
  stage: deploy-test
  only:
    - develop
  script:
    - kubectl set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE -n test-masa-blazor
    - kubectl set image deployment/masa-blazor-docs-wasm masa-blazor-docs-wasm=$IMAGEWASM -n test-masa-blazor
  retry: 2
  when: manual

packer-prd:
  # image: proget-hz.lonsid.cn/masa-blazor/dotnet/sdk:6.0-forlinux
  #image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0-nodejs14.17.6
  image: registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0.100-preview.7-nodejs14.16.1
  stage: packer-prd
  only:
    - tags 
  script:
    - ls 
    - ls src/
    - node -v
    - dotnet --version
    - git clone -b develop http://gitlab-hz.lonsid.cn/MASA-Stack/Framework/BlazorComponent.git ./src/BlazorComponent
    - dotnet workload install wasm-tools
    - dotnet build src
    - dotnet pack src --include-symbols -p:PackageVersion=$CI_COMMIT_TAG
    - dotnet nuget push "**/*.symbols.nupkg" -k $nugetkey -s https://api.nuget.org/v3/index.json
  artifacts:
    expire_in: 1 day
    paths:
      - ./src/BlazorComponent
  retry: 2

docker-prd:
  image: docker:17.05.0
  stage: docker-prd
  only:
    - tags
  before_script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN
  services:
    - name: registry.cn-hangzhou.aliyuncs.com/masa/library:docker-17.05.01-dind
  script:
    - docker build -t $IMAGE_PRD .
    - docker push $IMAGE_PRD
    - docker build -f Dockerfile.wasm -t $IMAGEWASM_PRD .
    - docker push $IMAGEWASM_PRD
  retry: 2

deploy-prd:
  image: registry.cn-hangzhou.aliyuncs.com/masa/kubectl:1.20.1-masa-blazor-prd
  stage: deploy-prd
  only:
    - tags
  script:
    - kubectl set image deployment/masa-blazor-docs masa-blazor-docs=$IMAGE_PRD -n masa-blazor
    - kubectl set image deployment/masa-blazor-docs-wasm masa-blazor-docs-wasm=$IMAGEWASM_PRD -n masa-blazor
  retry: 2
  when: manual  
